### ISSUE TITLE
Segfault on dummy conf file

### ISSUE THREAD

**Issue by Artymort** [fanglingsu/vimb#188]
Hi,

Starting a freshly compiled vimb on my computer via './vimb -c cfg" and a wrong configuration file (here containing only "foo") leads to a segfault on my computer. I had a look and i can't go deeper that around line 300 in main : 
```C
gtk_text_buffer_set_text(vb.gui.buffer, text, -1);
```

I did some testing and I believe the problem does not come from text, neither from its size (or here the -1). Creating a new buffer removes the segfault (but then there is no error message).

I believe the problem is deeper than that, since any error message could lead to a segfault as text seems well-formed ?

Here is the backtrace I obtained :

```
#0  0x000000000041698a in buffer_changed_cb (buffer=0x744040, data=0x0) at main.c:602
#1  0x00007ffff37ca175 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff37dba5c in ?? () from /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff37e46f8 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff37e495f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff57ade55 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff37ca175 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff37db952 in ?? () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff37e46f8 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff37e495f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff57b15df in gtk_text_buffer_set_text () from /usr/lib/libgtk-x11-2.0.so.0
#11 0x0000000000415bd6 in vb_set_input_text (text=0x9d4f00 "Unknown command: foo") at main.c:302
#12 0x0000000000415b69 in input_print (force=0, type=VB_MSG_ERROR, hide=1, message=0x9d4f00 "Unknown command: foo")
    at main.c:284
#13 0x0000000000415936 in vb_echo (type=VB_MSG_ERROR, hide=1, error=0x41d27e "Unknown command: %s") at main.c:168
#14 0x000000000040c6c3 in parse_command_name (input=0x7fffffffe3d8, arg=0xbd5ac0) at ex.c:606
#15 0x000000000040c3a4 in parse (input=0x7fffffffe3d8, arg=0xbd5ac0, nohist=0x7fffffffe3d4) at ex.c:524
#16 0x000000000040c244 in ex_run_string (input=0x9d4e10 "foo", enable_history=0) at ex.c:486
#17 0x0000000000417b0f in read_config () at main.c:1099
#18 0x00000000004179e7 in init_core () at main.c:1037
#19 0x00000000004193c9 in main (argc=1, argv=0x7fffffffe5d8) at main.c:1799
```

**Comment by fanglingsu** [comment]
Thank you for reporting that. I can reproduce the segfault.

**Comment by fanglingsu** [comment]
For me it works now. If this works for you too, please close the issue.

**Comment by Artymort** [comment]
Works here too. Thanks and good job, you're doing great :+1:
